In [0]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [0]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)
      

120

In [0]:
#method
#def test(self,para1,para2)
class demo2:
  def accept(self,p1,p2):
    a=p1
    b=p2
    return
  def display(self):
    print("a=",a)
    print("b=",b)
    
demo2().display

<bound method demo2.display of <__main__.demo2 object at 0x7f018aa29240>>

In [0]:
class Demo2:
    def __init_(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

TypeError: ignored

In [2]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4)(5,6)])
print(a2.shape)

(2, 3)


TypeError: ignored

In [3]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
#append some data-Horizantally
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [6]:
a1=np.random.normal(5,0,5)
print(a1)

[5. 5. 5. 5. 5.]


In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones((4,3),dtype=np.int64)
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
a=np.matrix(np.ones(4,4),dtype=np.int64)
print(A)

TypeError: ignored